# Generated by Django 4.1.4 on 2022-12-11 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'PDF', 'verbose_name_plural': 'PDFS'},
        ),
    ]
