# Generated by Django 4.1.4 on 2022-12-11 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_about_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='curriculum',
            field=models.FileField(upload_to='curriculum', verbose_name='Curriculum PDF'),
        ),
    ]
