# Generated by Django 4.1.4 on 2022-12-10 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='year_in_school',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='Tags',
            field=models.CharField(choices=[('API', 'APIS'), ('django', 'DJANGO'), ('flask', 'FLASK'), ('scripts', 'SCRIPTS')], default='API', max_length=7),
        ),
    ]
