# Generated by Django 4.1.4 on 2022-12-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_proyecto_year_in_school_proyecto_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='img',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='Imagen_url',
            field=models.URLField(null=True),
        ),
    ]
