# Generated by Django 4.1.4 on 2022-12-11 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_project_delete_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image_url',
            field=models.URLField(default='', verbose_name='Imagen url'),
        ),
    ]
