# Generated by Django 4.1.4 on 2022-12-11 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_education_experience_delete_educacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='university',
        ),
    ]
