# Generated by Django 4.1.4 on 2022-12-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_remove_experience_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='company',
            field=models.CharField(default='', max_length=50, verbose_name='Empresa'),
        ),
    ]
